print("INGRESA DATOS")
print("-------------------------")
vnom = input("ingresa tu nombre: ")
vedad = input("ingresa tu edad: ")
print("-------------------------")
print(f"tu nombre es{vnom}")
print(f"tu edad es{vedad}")
print("programa finalizado")